---
abstract: 'Advanced Message Queue Protocol (de)serialization and representation'
author:
  - 'Eric Waters <ewaters@gmail.com>'
build_requires:
  File::Temp: 0.19
  Test::Deep: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-AMQP
provides:
  Net::AMQP:
    file: lib/Net/AMQP.pm
    version: 0.04
  Net::AMQP::Common:
    file: lib/Net/AMQP/Common.pm
    version: 0.04
  Net::AMQP::Frame:
    file: lib/Net/AMQP/Frame.pm
    version: 0.04
  Net::AMQP::Frame::Body:
    file: lib/Net/AMQP/Frame/Body.pm
    version: 0.04
  Net::AMQP::Frame::Header:
    file: lib/Net/AMQP/Frame/Header.pm
    version: 0.04
  Net::AMQP::Frame::Heartbeat:
    file: lib/Net/AMQP/Frame/Heartbeat.pm
    version: 0.04
  Net::AMQP::Frame::Method:
    file: lib/Net/AMQP/Frame/Method.pm
    version: 0.04
  Net::AMQP::Frame::OOBBody:
    file: lib/Net/AMQP/Frame/OOBBody.pm
    version: 0.04
  Net::AMQP::Frame::OOBHeader:
    file: lib/Net/AMQP/Frame/OOBHeader.pm
    version: 0.04
  Net::AMQP::Frame::OOBMethod:
    file: lib/Net/AMQP/Frame/OOBMethod.pm
    version: 0.04
  Net::AMQP::Frame::Trace:
    file: lib/Net/AMQP/Frame/Trace.pm
    version: 0.04
  Net::AMQP::Protocol:
    file: lib/Net/AMQP/Protocol.pm
    version: 0.04
  Net::AMQP::Protocol::Base:
    file: lib/Net/AMQP/Protocol/Base.pm
    version: 0.04
  Net::AMQP::Protocol::v0_8:
    file: lib/Net/AMQP/Protocol/v0_8.pm
    version: 0.04
requires:
  Class::Accessor: 0
  Class::Data::Inheritable: 0
  XML::LibXML: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
